services:
  - type: web
    name: loconav-webhook-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node webhook-server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
